In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the data

In [3]:
airline_financials = pd.read_csv("data/airline_financials.csv")
aviation_incidents = pd.read_csv("data/aviation_incidents.csv")
fleet_orders = pd.read_csv("data/fleet_orders.csv")
passenger_traffic = pd.read_csv("data/passenger_traffic.csv")
route_performance = pd.read_csv("data/route_performance.csv")

# 2. Review the data

### 2.1 airline_financials

In [4]:
airline_financials.head()

,year,airline_name,iata_code,country_iso3,region,business_model,revenue_usd_bn,operating_margin_pct,operating_income_usd_bn,passengers_carried_m,load_factor_pct,fleet_size_est
0,2010,Delta Air Lines,DAL,USA,North America,legacy,32.09,3.4,1.09,48.1,84.5,160
1,2011,Delta Air Lines,DAL,USA,North America,legacy,34.54,1.1,0.39,51.8,80.4,172
2,2012,Delta Air Lines,DAL,USA,North America,legacy,35.50,5.2,1.85,53.2,83.0,177
3,2013,Delta Air Lines,DAL,USA,North America,legacy,36.20,8.2,2.97,54.3,84.6,181
4,2014,Delta Air Lines,DAL,USA,North America,legacy,39.00,8.8,3.44,58.5,83.9,194

In [5]:
airline_financials.dtypes

year                         int64
airline_name                object
iata_code                   object
country_iso3                object
region                      object
business_model              object
revenue_usd_bn             float64
operating_margin_pct       float64
operating_income_usd_bn    float64
passengers_carried_m       float64
load_factor_pct            float64
fleet_size_est               int64
dtype: object

In [6]:
airline_financials.shape

(497, 12)

In [7]:
airline_financials.isna().sum()

year                       0
airline_name               0
iata_code                  0
country_iso3               0
region                     0
business_model             0
revenue_usd_bn             0
operating_margin_pct       0
operating_income_usd_bn    0
passengers_carried_m       0
load_factor_pct            0
fleet_size_est             0
dtype: int64

### 2.2 aviation_incidents

In [8]:
aviation_incidents.head()

,incident_id,date,year,month,flight_number,airline,aircraft_type,severity,fatalities,location,description,is_fatal,is_geopolitical,is_boeing,is_airbus
0,AV001,2010-04-10,2010,4,PLF101,Polish AF,Tu-154,fatal_crash,96,"Smolensk, Russia",Polish presidential plane crash,1,0,0,0
1,AV002,2010-05-22,2010,5,IX812,Air India Express,B737-800,fatal_crash,158,"Mangalore, India",Runway overrun,1,0,1,0
2,AV003,2011-07-08,2011,7,PIA8264,Hewa Bora Airways,B727,fatal_crash,81,"Kisangani, DRC",Severe weather landing,1,0,1,0
3,AV004,2012-04-20,2012,4,BSC213,Bhoja Air,B737-200,fatal_crash,127,"Islamabad, Pakistan",Crashed near airport,1,0,1,0
4,AV005,2013-07-06,2013,7,OZ214,Asiana Airlines,B777-200,fatal_crash,3,"San Francisco, USA",Hard landing short of runway,1,0,1,0

In [9]:
aviation_incidents.dtypes

incident_id        object
date               object
year                int64
month               int64
flight_number      object
airline            object
aircraft_type      object
severity           object
fatalities          int64
location           object
description        object
is_fatal            int64
is_geopolitical     int64
is_boeing           int64
is_airbus           int64
dtype: object

In [10]:
aviation_incidents.shape

(40, 15)

### 2.3 fleet_orders

In [11]:
fleet_orders.head()

,year,manufacturer,aircraft_family,orders_gross,orders_net,deliveries,backlog_end_of_year,is_widebody,is_narrowbody,is_regional
0,2010,Airbus,A320 family,452,452,401,2440,0,1,0
1,2010,Airbus,A330/340/350/380,122,122,109,776,1,0,0
2,2010,Boeing,737,506,506,376,2079,0,1,0
3,2010,Boeing,747/767/777/787,24,24,86,1057,1,0,0
4,2011,Airbus,A320 family,719,719,431,3061,0,1,0

In [12]:
fleet_orders.dtypes

year                    int64
manufacturer           object
aircraft_family        object
orders_gross            int64
orders_net              int64
deliveries              int64
backlog_end_of_year     int64
is_widebody             int64
is_narrowbody           int64
is_regional             int64
dtype: object

In [13]:
fleet_orders.shape

(86, 10)

### 2.4 passenger_traffic

In [14]:
passenger_traffic.head()

,year_month,year,month,region,rpk_billions,ask_billions,load_factor_pct
0,2010-01,2010,1,North America,61.73,76.45,80.8
1,2010-02,2010,2,North America,58.63,72.13,81.3
2,2010-03,2010,3,North America,60.16,72.79,82.6
3,2010-04,2010,4,North America,64.07,76.80,83.4
4,2010-05,2010,5,North America,69.43,85.85,80.9

In [15]:
passenger_traffic.dtypes

year_month          object
year                 int64
month                int64
region              object
rpk_billions       float64
ask_billions       float64
load_factor_pct    float64
dtype: object

In [16]:
passenger_traffic.shape

(1176, 7)

### 2.5 route_performance

In [17]:
route_performance.head()

,year,route,origin_iata,destination_iata,distance_km,region,main_airlines,annual_passengers_m,avg_fare_usd,weekly_frequency_est,annual_revenue_usd_m
0,2015,Jeju-Seoul,CJU,GMP,451,Asia,"Korean Air, Asiana, JeJu Air",6.37,50.0,19,320.5
1,2018,Jeju-Seoul,CJU,GMP,451,Asia,"Korean Air, Asiana, JeJu Air",7.92,68.0,22,539.4
2,2019,Jeju-Seoul,CJU,GMP,451,Asia,"Korean Air, Asiana, JeJu Air",7.65,65.0,21,498.0
3,2020,Jeju-Seoul,CJU,GMP,451,Asia,"Korean Air, Asiana, JeJu Air",2.21,21.0,4,45.4
4,2021,Jeju-Seoul,CJU,GMP,451,Asia,"Korean Air, Asiana, JeJu Air",3.57,34.0,10,121.5

In [18]:
route_performance.dtypes

year                      int64
route                    object
origin_iata              object
destination_iata         object
distance_km               int64
region                   object
main_airlines            object
annual_passengers_m     float64
avg_fare_usd            float64
weekly_frequency_est      int64
annual_revenue_usd_m    float64
dtype: object

In [19]:
route_performance.shape

(400, 11)

# 3. Explanatory Data Analysis(EDA)

In [21]:
airline_financials["airline_name"].value_counts()

airline_name
Delta Air Lines          17
United Airlines          17
LATAM Airlines           17
Saudia                   17
Etihad                   17
Qatar Airways            17
Emirates                 17
AirAsia                  17
IndiGo                   17
Korean Air               17
Cathay Pacific           17
Singapore Airlines       17
ANA Holdings             17
Japan Airlines           17
China Eastern            17
Air China                17
China Southern           17
Aeroflot                 17
Turkish Airlines         17
easyJet                  17
Ryanair                  17
Air France-KLM           17
IAG (British Airways)    17
Lufthansa Group          17
JetBlue                  17
Alaska Airlines          17
Southwest Airlines       17
American Airlines        17
Azul                     17
Riyadh Air                4
Name: count, dtype: int64